name: "YAML Read"
description: "This action reads a YAML configuration files, with support to variable interpolation"
author: "pietrobolcato"
branding:
  icon: box
  color: blue
inputs:
  config:
    description: "Config file name"
    required: true
    default: ""
  base-config-object:
    description: "Base object (as json string) to merge the yaml file with"
    required: false
    default: ""
  key-path-pattern:
    description: "Key path pattern to filter out in the yaml file (or to merge with the base-config-object if merge is true)"
    required: false
    default: ""
  env-var-prefix:
    description: "Prefix that will be added as the prefix to the environment variables output"
    required: false
    default: ""
  merge:
    description: "Works in conjuection with the key-path input, if true, the key-path will be merged with the root of the yaml file"
    required: false
runs:
  using: "node20"
  main: "action_read_yaml/index.js"
